DEBUG 2017-11-17 22:52:40,188: 	 Executing command: 'status'
DEBUG 2017-11-17 22:52:40,189: 	 Found CRAB cache file /u/user/sha/.crab3
DEBUG 2017-11-17 22:52:40,198: 	 Checking credentials
DEBUG 2017-11-17 22:52:40,198: 	 Found proxy file /tmp/x509up_u40993
DEBUG 2017-11-17 22:52:40,198: 	 Getting proxy life time left
DEBUG 2017-11-17 22:52:40,805: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u40993 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2017-11-17 22:52:40,805: 	 Proxy valid for 00:00:00 hours
DEBUG 2017-11-17 22:52:40,805: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2017-11-17 22:54:21,857: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2017-11-17 22:54:22,571: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u40993 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2017-11-17 22:54:23,178: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u40993 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
ERROR 2017-11-17 22:54:23,179: 	 Problems creating proxy.
ERROR 2017-11-17 22:54:23,180: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 38, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2017-11-22 09:50:57,968: 	 Executing command: 'status'
DEBUG 2017-11-22 09:50:57,969: 	 Found CRAB cache file /u/user/sha/.crab3
DEBUG 2017-11-22 09:50:58,006: 	 Checking credentials
DEBUG 2017-11-22 09:50:58,006: 	 Found proxy file /tmp/x509up_u40993
DEBUG 2017-11-22 09:50:58,006: 	 Getting proxy life time left
DEBUG 2017-11-22 09:50:59,227: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u40993 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2017-11-22 09:50:59,227: 	 Proxy valid for 00:00:00 hours
DEBUG 2017-11-22 09:50:59,227: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2017-11-22 09:52:36,926: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 1
DEBUG 2017-11-22 09:52:38,345: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u40993 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2017-11-22 09:52:39,564: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u40993 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
ERROR 2017-11-22 09:52:39,564: 	 Problems creating proxy.
ERROR 2017-11-22 09:52:39,565: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 38, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
